apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: 'Solr for search in the cloud. '
    iconClass: icon-solr
    openshift.io/display-name: Solr
    tags: solr
    version: 7.1.0
  creationTimestamp: '2019-05-14T22:12:00Z'
  name: computate-solr
  namespace: computateorg
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: solr-data-volume-claim
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        description: Solr port.
      labels:
        application: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      ports:
        - name: solr-port
          port: 8080
          targetPort: 8080
      selector:
        deploymentConfig: '${APPLICATION_NAME}'
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        application: '${APPLICATION_NAME}'
      name: '${APPLICATION_NAME}'
    spec:
      replicas: 1
      selector:
        deploymentConfig: '${APPLICATION_NAME}'
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            application: '${APPLICATION_NAME}'
            deploymentConfig: '${APPLICATION_NAME}'
          name: '${APPLICATION_NAME}'
        spec:
          containers:
            - env: []
              image: computate/computate-solr
              name: '${APPLICATION_NAME}'
              volumeMounts:
                - mountPath: /srv/solr/data
                  name: solr-data-volume
              ports:
                - name: solr-port
                  containerPort: 8080
                  protocol: TCP
              securityContext:
                privileged: false
          volumes:
            - name: solr-data-volume
              persistentVolumeClaim:
                claimName: solr-data-volume-claim
      triggers:
        - type: ConfigChange
parameters:
  - description: The name for the application.
    displayName: Application Name
    name: APPLICATION_NAME
    required: true
    value: computate-solr
  - name: SOLR_PORT
    value: '8080'
  - name: SOLR_CONFIG
    value: 'computate'
  - name: SOLR_COLLECTION
    value: 'site'
  - name: ZK_HOSTNAME
    value: 'localhost'
  - name: ZK_CLIENT_PORT
    value: '8080'

